// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxbHnJvnTsYHa-YOC7djWUr27UDU0rxu0',
    appId: '1:242618599501:web:13375950a603ff68007404',
    messagingSenderId: '242618599501',
    projectId: 'chatterloop',
    authDomain: 'chatterloop.firebaseapp.com',
    storageBucket: 'chatterloop.appspot.com',
    measurementId: 'G-W77DPVGPHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95H8bjinI_e1GLY4m7F0DMnaZeRCu8zE',
    appId: '1:242618599501:android:10f13c71ed4733df007404',
    messagingSenderId: '242618599501',
    projectId: 'chatterloop',
    storageBucket: 'chatterloop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgZM5U5ulWTw1FCuw2NnRnEFJCL49Tp8',
    appId: '1:242618599501:ios:04ce189047af9747007404',
    messagingSenderId: '242618599501',
    projectId: 'chatterloop',
    storageBucket: 'chatterloop.appspot.com',
    androidClientId: '242618599501-di8d5il7kdreifnkg6l6r0tbuc88t9se.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterloopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgZM5U5ulWTw1FCuw2NnRnEFJCL49Tp8',
    appId: '1:242618599501:ios:04ce189047af9747007404',
    messagingSenderId: '242618599501',
    projectId: 'chatterloop',
    storageBucket: 'chatterloop.appspot.com',
    androidClientId: '242618599501-di8d5il7kdreifnkg6l6r0tbuc88t9se.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterloopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDILgwEwV5dL14N5P0a5ONUW0Dr17oQkgs',
    appId: '1:242618599501:web:8bb4017311a7b822007404',
    messagingSenderId: '242618599501',
    projectId: 'chatterloop',
    authDomain: 'chatterloop.firebaseapp.com',
    storageBucket: 'chatterloop.appspot.com',
    measurementId: 'G-7GMXFCQY5N',
  );
}
